alelo/base/urls.py
from django.conf.urls import url
from django.urls import path

from alelo.base.views import home, janeiro, apagar_valor_janeiro, fevereiro, marco, abril, maio, junho, julho, agosto, \
    setembro, outubro, novembro, dezembro, apagar_valor_fevereiro, apagar_valor_marco, apagar_valor_abril, \
    apagar_valor_maio, apagar_valor_junho, apagar_valor_julho, apagar_valor_agosto, apagar_valor_setembro, \
    apagar_valor_outubro, apagar_valor_novembro, apagar_valor_dezembro

app_name = 'base'

urlpatterns = [
    path('', home, name='home'),
    path('janeiro/', janeiro, name='janeiro'),
    path('fevereiro/', fevereiro, name='fevereiro'),
    path('marco/', marco, name='marco'),
    path('abril/', abril, name='abril'),
    path('maio/', maio, name='maio'),
    path('junho/', junho, name='junho'),
    path('julho/', julho, name='julho'),
    path('agosto/', agosto, name='agosto'),
    path('setembro/', setembro, name='setembro'),
    path('outubro/', outubro, name='outubro'),
    path('novembro/', novembro, name='novembro'),
    path('dezembro/', dezembro, name='dezembro'),
    url(r'janeiro/delete/(?P<pk>[0-9]+)/$', apagar_valor_janeiro, name='apagar_valor_janeiro'),
    url(r'fevereiro/delete/(?P<pk>[0-9]+)/$', apagar_valor_fevereiro, name='apagar_valor_fevereiro'),
    url(r'marco/delete/(?P<pk>[0-9]+)/$', apagar_valor_marco, name='apagar_valor_marco'),
    url(r'abril/delete/(?P<pk>[0-9]+)/$', apagar_valor_abril, name='apagar_valor_abril'),
    url(r'maio/delete/(?P<pk>[0-9]+)/$', apagar_valor_maio, name='apagar_valor_maio'),
    url(r'junho/delete/(?P<pk>[0-9]+)/$', apagar_valor_junho, name='apagar_valor_junho'),
    url(r'julho/delete/(?P<pk>[0-9]+)/$', apagar_valor_julho, name='apagar_valor_julho'),
    url(r'agosto/delete/(?P<pk>[0-9]+)/$', apagar_valor_agosto, name='apagar_valor_agosto'),
    url(r'setembro/delete/(?P<pk>[0-9]+)/$', apagar_valor_setembro, name='apagar_valor_setembro'),
    url(r'outubro/delete/(?P<pk>[0-9]+)/$', apagar_valor_outubro, name='apagar_valor_outubro'),
    url(r'novembro/delete/(?P<pk>[0-9]+)/$', apagar_valor_novembro, name='apagar_valor_novembro'),
    url(r'dezembro/delete/(?P<pk>[0-9]+)/$', apagar_valor_dezembro, name='apagar_valor_dezembro'),
]

alelo/urls.py
from django.contrib import admin
from django.urls import path, include

from alelo import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contas/', include('django.contrib.auth.urls')),
    path('', include('alelo.base.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

alelo/base/models.py
from django.db import models


class Janeiro(models.Model):
    valor = models.FloatField(max_length=10)
    criado_em = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.valor


class Fevereiro(models.Model):
    valor = models.FloatField(max_length=10)
    criado_em = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.valor


class Marco(models.Model):
    valor = models.FloatField(max_length=10)
    criado_em = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.valor


class Abril(models.Model):
    valor = models.FloatField(max_length=10)
    criado_em = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.valor


class Maio(models.Model):
    valor = models.FloatField(max_length=10)
    criado_em = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.valor


class Junho(models.Model):
    valor = models.FloatField(max_length=10)
    criado_em = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.valor


class Julho(models.Model):
    valor = models.FloatField(max_length=10)
    criado_em = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.valor


class Agosto(models.Model):
    valor = models.FloatField(max_length=10)
    criado_em = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.valor


class Setembro(models.Model):
    valor = models.FloatField(max_length=10)
    criado_em = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.valor


class Outubro(models.Model):
    valor = models.FloatField(max_length=10)
    criado_em = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.valor


class Novembro(models.Model):
    valor = models.FloatField(max_length=10)
    criado_em = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.valor


class Dezembro(models.Model):
    valor = models.FloatField(max_length=10)
    criado_em = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.valor

alelo/base/forms.py
from django.forms import ModelForm

from alelo.base.models import Janeiro, Dezembro, Novembro, Outubro, Setembro, Agosto, Julho, Junho, Maio, Abril, Marco, \
    Fevereiro


class JaneiroValorNovoForm(ModelForm):
    class Meta:
        model = Janeiro
        fields = ['valor']


class FevereiroValorNovoForm(ModelForm):
    class Meta:
        model = Fevereiro
        fields = ['valor']


class MarcoValorNovoForm(ModelForm):
    class Meta:
        model = Marco
        fields = ['valor']


class AbrilValorNovoForm(ModelForm):
    class Meta:
        model = Abril
        fields = ['valor']


class MaioValorNovoForm(ModelForm):
    class Meta:
        model = Maio
        fields = ['valor']


class JunhoValorNovoForm(ModelForm):
    class Meta:
        model = Junho
        fields = ['valor']


class JulhoValorNovoForm(ModelForm):
    class Meta:
        model = Julho
        fields = ['valor']


class AgostoValorNovoForm(ModelForm):
    class Meta:
        model = Agosto
        fields = ['valor']


class SetembroValorNovoForm(ModelForm):
    class Meta:
        model = Setembro
        fields = ['valor']


class OutubroValorNovoForm(ModelForm):
    class Meta:
        model = Outubro
        fields = ['valor']


class NovembroValorNovoForm(ModelForm):
    class Meta:
        model = Novembro
        fields = ['valor']


class DezembroValorNovoForm(ModelForm):
    class Meta:
        model = Dezembro
        fields = ['valor']

alelo/base/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from alelo.base.forms import JaneiroValorNovoForm, FevereiroValorNovoForm, MarcoValorNovoForm, AbrilValorNovoForm, \
    MaioValorNovoForm, JunhoValorNovoForm, JulhoValorNovoForm, AgostoValorNovoForm, SetembroValorNovoForm, \
    OutubroValorNovoForm, NovembroValorNovoForm, DezembroValorNovoForm
from alelo.base.models import Janeiro, Fevereiro, Marco, Abril, Maio, Junho, Julho, Agosto, Setembro, Outubro, Novembro, \
    Dezembro


def home(request):
    return render(request, 'base/home.html')


# Mês - Janeiro
@login_required
def janeiro(request):
    if request.method == 'POST':
        form = JaneiroValorNovoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('base:janeiro'))
        else:
            valores_mes = Janeiro.objects.all()
            return render(request, 'base/meses/janeiro.html', {'form': form, 'valores_mes': valores_mes}, status=400)

    total_mes_janeiro_dct = Janeiro.objects.aggregate(Sum('valor'))
    total_mes_janeiro = total_mes_janeiro_dct['valor__sum']
    valores_mes = Janeiro.objects.all()
    return render(request, 'base/meses/janeiro.html',
                  {'valores_mes': valores_mes, 'total_mes_janeiro': total_mes_janeiro})


def apagar_valor_janeiro(request, pk):
    valor = get_object_or_404(Janeiro, pk=pk)

    if request.method == 'POST':
        valor.delete()
        return HttpResponseRedirect(reverse('base:janeiro'))
    return render(request, 'base/meses/janeiro.html', {'valor': valor})


# Mês - Fevereiro
@login_required
def fevereiro(request):
    if request.method == 'POST':
        form = FevereiroValorNovoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('base:fevereiro'))
        else:
            valores_mes = Fevereiro.objects.all()
            return render(request, 'base/meses/fevereiro.html', {'form': form, 'valores_mes': valores_mes}, status=400)

    total_mes_fevereiro_dct = Fevereiro.objects.aggregate(Sum('valor'))
    total_mes_fevereiro = total_mes_fevereiro_dct['valor__sum']
    valores_mes = Fevereiro.objects.all()
    return render(request, 'base/meses/fevereiro.html',
                  {'valores_mes': valores_mes, 'total_mes_fevereiro': total_mes_fevereiro})


def apagar_valor_fevereiro(request, pk):
    valor = get_object_or_404(Fevereiro, pk=pk)

    if request.method == 'POST':
        valor.delete()
        return HttpResponseRedirect(reverse('base:fevereiro'))
    return render(request, 'base/meses/fevereiro.html', {'valor': valor})


# Mês - Março
@login_required
def marco(request):
    if request.method == 'POST':
        form = MarcoValorNovoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('base:marco'))
        else:
            valores_mes = Marco.objects.all()
            return render(request, 'base/meses/marco.html', {'form': form, 'valores_mes': valores_mes}, status=400)

    total_mes_marco_dct = Marco.objects.aggregate(Sum('valor'))
    total_mes_marco = total_mes_marco_dct['valor__sum']
    valores_mes = Marco.objects.all()
    return render(request, 'base/meses/marco.html', {'valores_mes': valores_mes, 'total_mes_marco': total_mes_marco})


def apagar_valor_marco(request, pk):
    valor = get_object_or_404(Marco, pk=pk)

    if request.method == 'POST':
        valor.delete()
        return HttpResponseRedirect(reverse('base:marco'))
    return render(request, 'base/meses/marco.html', {'valor': valor})


# Mês - Abril
@login_required
def abril(request):
    if request.method == 'POST':
        form = AbrilValorNovoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('base:abril'))
        else:
            valores_mes = Abril.objects.all()
            return render(request, 'base/meses/abril.html', {'form': form, 'valores_mes': valores_mes}, status=400)

    total_mes_abril_dct = Abril.objects.aggregate(Sum('valor'))
    total_mes_abril = total_mes_abril_dct['valor__sum']
    valores_mes = Abril.objects.all()
    return render(request, 'base/meses/abril.html', {'valores_mes': valores_mes, 'total_mes_abril': total_mes_abril})


def apagar_valor_abril(request, pk):
    valor = get_object_or_404(Abril, pk=pk)

    if request.method == 'POST':
        valor.delete()
        return HttpResponseRedirect(reverse('base:abril'))
    return render(request, 'base/meses/abril.html', {'valor': valor})


# Mês - Maio
@login_required
def maio(request):
    if request.method == 'POST':
        form = MaioValorNovoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('base:maio'))
        else:
            valores_mes = Maio.objects.all()
            return render(request, 'base/meses/maio.html', {'form': form, 'valores_mes': valores_mes}, status=400)

    total_mes_maio_dct = Maio.objects.aggregate(Sum('valor'))
    total_mes_maio = total_mes_maio_dct['valor__sum']
    valores_mes = Maio.objects.all()
    return render(request, 'base/meses/maio.html', {'valores_mes': valores_mes, 'total_mes_maio': total_mes_maio})


def apagar_valor_maio(request, pk):
    valor = get_object_or_404(Maio, pk=pk)

    if request.method == 'POST':
        valor.delete()
        return HttpResponseRedirect(reverse('base:maio'))
    return render(request, 'base/meses/maio.html', {'valor': valor})


# Mês - Junho
@login_required
def junho(request):
    if request.method == 'POST':
        form = JunhoValorNovoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('base:junho'))
        else:
            valores_mes = Junho.objects.all()
            return render(request, 'base/meses/junho.html', {'form': form, 'valores_mes': valores_mes}, status=400)

    total_mes_junho_dct = Junho.objects.aggregate(Sum('valor'))
    total_mes_junho = total_mes_junho_dct['valor__sum']
    valores_mes = Junho.objects.all()
    return render(request, 'base/meses/junho.html', {'valores_mes': valores_mes, 'total_mes_junho': total_mes_junho})


def apagar_valor_junho(request, pk):
    valor = get_object_or_404(Junho, pk=pk)

    if request.method == 'POST':
        valor.delete()
        return HttpResponseRedirect(reverse('base:junho'))
    return render(request, 'base/meses/junho.html', {'valor': valor})


# Mês - Julho
@login_required
def julho(request):
    if request.method == 'POST':
        form = JulhoValorNovoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('base:julho'))
        else:
            valores_mes = Julho.objects.all()
            return render(request, 'base/meses/julho.html', {'form': form, 'valores_mes': valores_mes}, status=400)

    total_mes_julho_dct = Julho.objects.aggregate(Sum('valor'))
    total_mes_julho = total_mes_julho_dct['valor__sum']
    valores_mes = Julho.objects.all()
    return render(request, 'base/meses/julho.html', {'valores_mes': valores_mes, 'total_mes_julho': total_mes_julho})


def apagar_valor_julho(request, pk):
    valor = get_object_or_404(Julho, pk=pk)

    if request.method == 'POST':
        valor.delete()
        return HttpResponseRedirect(reverse('base:julho'))
    return render(request, 'base/meses/julho.html', {'valor': valor})


# Mês - Agosto
@login_required
def agosto(request):
    if request.method == 'POST':
        form = AgostoValorNovoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('base:agosto'))
        else:
            valores_mes = Agosto.objects.all()
            return render(request, 'base/meses/agosto.html', {'form': form, 'valores_mes': valores_mes}, status=400)

    total_mes_agosto_dct = Agosto.objects.aggregate(Sum('valor'))
    total_mes_agosto = total_mes_agosto_dct['valor__sum']
    valores_mes = Agosto.objects.all()
    return render(request, 'base/meses/agosto.html', {'valores_mes': valores_mes, 'total_mes_agosto': total_mes_agosto})


def apagar_valor_agosto(request, pk):
    valor = get_object_or_404(Agosto, pk=pk)

    if request.method == 'POST':
        valor.delete()
        return HttpResponseRedirect(reverse('base:agosto'))
    return render(request, 'base/meses/agosto.html', {'valor': valor})


# Mês - Setembro
@login_required
def setembro(request):
    if request.method == 'POST':
        form = SetembroValorNovoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('base:setembro'))
        else:
            valores_mes = Setembro.objects.all()
            return render(request, 'base/meses/setembro.html', {'form': form, 'valores_mes': valores_mes}, status=400)

    total_mes_setembro_dct = Setembro.objects.aggregate(Sum('valor'))
    total_mes_setembro = total_mes_setembro_dct['valor__sum']
    valores_mes = Setembro.objects.all()
    return render(request, 'base/meses/setembro.html',
                  {'valores_mes': valores_mes, 'total_mes_setembro': total_mes_setembro})


def apagar_valor_setembro(request, pk):
    valor = get_object_or_404(Setembro, pk=pk)

    if request.method == 'POST':
        valor.delete()
        return HttpResponseRedirect(reverse('base:setembro'))
    return render(request, 'base/meses/setembro.html', {'valor': valor})


# Mês - Outubro
@login_required
def outubro(request):
    if request.method == 'POST':
        form = OutubroValorNovoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('base:outubro'))
        else:
            valores_mes = Outubro.objects.all()

alelo/base/templates/base/meses/abril.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Alelo - Abril{% endblock title %}
{% block body %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">

                <div class="jumbotron">
                    <h2>
                        Olá, {{ user.first_name }}!
                    </h2>
                    <p>
                        Para cadastrar algum valor para o mês de <b>Abril</b> basta digitar o mesmo
                        no campo de texto abaixo e clicar no botão 'Adicionar'.
                    </p>

                </div>

                <form action="{% url 'base:abril' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="formGroupExampleInput">Adicionar valor</label>
                        <input type="number" name="valor" step="0.01" min="0.01" class="form-control"
                               id="formGroupExampleInput"
                               placeholder="R$" required>
                        <small class="form-text text-muted">{{ form.valor.errors }}</small>
                        <br>
                        <button type="submit" class="btn btn-outline-primary">Adicionar</button>

                    </div>
                </form>

                <table class="table">
                    <thead>
                    <tr>
                        <th>
                            #
                        </th>
                        <th>
                            Valor
                        </th>
                        <th>
                            Data
                        </th>
                        <th>
                            Excluir
                        </th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for valor in valores_mes %}
                        <tr>
                            <td>
                                {{ valor.pk }}
                            </td>
                            <td>
                                R$ {{ valor.valor }}
                            </td>
                            <td>
                                {{ valor.criado_em }}
                            </td>
                            <td>

                                <form action="{% url 'base:apagar_valor_abril' valor.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger">Excluir</button>
                                </form>

                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>

                <div class="jumbotron">
                    <p class="lead">Total</p>
                    <hr class="my-4">

                    {% if total_mes_abril == None %}
                        <h2>Vazio</h2>
                    {% else %}
                        <h2>R$ {{ total_mes_abril|floatformat:2 }}</h2>
                    {% endif %}
                </div>

            </div>
        </div>
    </div>

{% endblock body %}

alelo/base/templates/base/meses/agosto.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Alelo - Agosto{% endblock title %}
{% block body %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">

                <div class="jumbotron">
                    <h2>
                        Olá, {{ user.first_name }}!
                    </h2>
                    <p>
                        Para cadastrar algum valor para o mês de <b>Agosto</b> basta digitar o mesmo
                        no campo de texto abaixo e clicar no botão 'Adicionar'.
                    </p>

                </div>

                <form action="{% url 'base:agosto' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="formGroupExampleInput">Adicionar valor</label>
                        <input type="number" name="valor" step="0.01" min="0.01" class="form-control"
                               id="formGroupExampleInput"
                               placeholder="R$" required>
                        <small class="form-text text-muted">{{ form.valor.errors }}</small>
                        <br>
                        <button type="submit" class="btn btn-outline-primary">Adicionar</button>

                    </div>
                </form>

                <table class="table">
                    <thead>
                    <tr>
                        <th>
                            #
                        </th>
                        <th>
                            Valor
                        </th>
                        <th>
                            Data
                        </th>
                        <th>
                            Excluir
                        </th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for valor in valores_mes %}
                        <tr>
                            <td>
                                {{ valor.pk }}
                            </td>
                            <td>
                                R$ {{ valor.valor }}
                            </td>
                            <td>
                                {{ valor.criado_em }}
                            </td>
                            <td>

                                <form action="{% url 'base:apagar_valor_agosto' valor.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger">Excluir</button>
                                </form>

                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>

                <div class="jumbotron">
                    <p class="lead">Total</p>
                    <hr class="my-4">

                    {% if total_mes_agosto == None %}
                        <h2>Vazio</h2>
                    {% else %}
                        <h2>R$ {{ total_mes_agosto|floatformat:2 }}</h2>
                    {% endif %}
                </div>

            </div>
        </div>
    </div>

{% endblock body %}

alelo/base/templates/base/meses/dezembro.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Alelo - Dezembro{% endblock title %}
{% block body %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">

                <div class="jumbotron">
                    <h2>
                        Olá, {{ user.first_name }}!
                    </h2>
                    <p>
                        Para cadastrar algum valor para o mês de <b>Dezembro</b> basta digitar o mesmo
                        no campo de texto abaixo e clicar no botão 'Adicionar'.
                    </p>

                </div>

                <form action="{% url 'base:dezembro' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="formGroupExampleInput">Adicionar valor</label>
                        <input type="number" name="valor" step="0.01" min="0.01" class="form-control"
                               id="formGroupExampleInput"
                               placeholder="R$" required>
                        <small class="form-text text-muted">{{ form.valor.errors }}</small>
                        <br>
                        <button type="submit" class="btn btn-outline-primary">Adicionar</button>

                    </div>
                </form>

                <table class="table">
                    <thead>
                    <tr>
                        <th>
                            #
                        </th>
                        <th>
                            Valor
                        </th>
                        <th>
                            Data
                        </th>
                        <th>
                            Excluir
                        </th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for valor in valores_mes %}
                        <tr>
                            <td>
                                {{ valor.pk }}
                            </td>
                            <td>
                                R$ {{ valor.valor }}
                            </td>
                            <td>
                                {{ valor.criado_em }}
                            </td>
                            <td>

                                <form action="{% url 'base:apagar_valor_dezembro' valor.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger">Excluir</button>
                                </form>

                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>

                <div class="jumbotron">
                    <p class="lead">Total</p>
                    <hr class="my-4">

                    {% if total_mes_dezembro == None %}
                        <h2>Vazio</h2>
                    {% else %}
                        <h2>R$ {{ total_mes_dezembro|floatformat:2 }}</h2>
                    {% endif %}
                </div>

            </div>
        </div>
    </div>

{% endblock body %}

alelo/base/templates/base/meses/novembro.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Alelo - Novembro{% endblock title %}
{% block body %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">

                <div class="jumbotron">
                    <h2>
                        Olá, {{ user.first_name }}!
                    </h2>
                    <p>
                        Para cadastrar algum valor para o mês de <b>Novembro</b> basta digitar o mesmo
                        no campo de texto abaixo e clicar no botão 'Adicionar'.
                    </p>

                </div>

                <form action="{% url 'base:novembro' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="formGroupExampleInput">Adicionar valor</label>
                        <input type="number" name="valor" step="0.01" min="0.01" class="form-control"
                               id="formGroupExampleInput"
                               placeholder="R$" required>
                        <small class="form-text text-muted">{{ form.valor.errors }}</small>
                        <br>
                        <button type="submit" class="btn btn-outline-primary">Adicionar</button>

                    </div>
                </form>

                <table class="table">
                    <thead>
                    <tr>
                        <th>
                            #
                        </th>
                        <th>
                            Valor
                        </th>
                        <th>
                            Data
                        </th>
                        <th>
                            Excluir
                        </th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for valor in valores_mes %}
                        <tr>
                            <td>
                                {{ valor.pk }}
                            </td>
                            <td>
                                R$ {{ valor.valor }}
                            </td>
                            <td>
                                {{ valor.criado_em }}
                            </td>
                            <td>

                                <form action="{% url 'base:apagar_valor_novembro' valor.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger">Excluir</button>
                                </form>

                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>

                <div class="jumbotron">
                    <p class="lead">Total</p>
                    <hr class="my-4">

                    {% if total_mes_novembro == None %}
                        <h2>Vazio</h2>
                    {% else %}
                        <h2>R$ {{ total_mes_novembro|floatformat:2 }}</h2>
                    {% endif %}
                </div>

            </div>
        </div>
    </div>

{% endblock body %}